LineageOS-20:
  kernel:
    - git clone https://github.com/LineageOS/android_kernel_samsung_sm8250.git -b lineage-20
  clang:
    - git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android-14.0.0_r2
  config:
    - make O=out ARCH=arm64 r8q_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out PGO=1 BOLT=1 LTO=full
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - r8q
  kernelSU:
    - stable-pin

Zenitsu:
  kernel:
    - git clone https://github.com/LineageOS/android_kernel_samsung_sm8250.git -b lineage-20
  clang:
    - git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android-14.0.0_r2
  config:
    - make O=out ARCH=arm64 r8q_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out PGO=1 BOLT=1 LTO=full
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - r8q
  kernelSU:
    - stable-pin

DivestOS-13:
  kernel:
    - git clone https://github.com/LineageOS/android_kernel_samsung_sm8250.git -b lineage-20
  clang:
    - git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android-14.0.0_r2
  config:
    - make O=out ARCH=arm64 r8q_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out PGO=1 BOLT=1 LTO=full
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - r8q
  kernelSU:
    - stable-pin

Sage-Android-14:
  kernel:
    - git clone https://github.com/LineageOS/android_kernel_samsung_sm8250.git -b lineage-21
  clang:
    - git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android-14.0.0_r2
  config:
    - make O=out ARCH=arm64 r8q_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out PGO=1 BOLT=1 LTO=full
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - r8q
  kernelSU:
    - stable-pin

Clean:
  out:
    - rm -rf out
  kernel:
    - make mrproper
  custom:
    - git status

KernelSU:
  version:
    stable-pin:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s kernelsu-version
    stable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
    unstable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

AnyKernel3:
  version:
    r8q:
      - git clone https://github.com/osm0sis/AnyKernel3.git -b master
    test:
      - echo "Test Success!"
